apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx
namespace: my-sample-project
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: docker.io/library/nginx:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
